name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Frontend testing job
  frontend-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }} # Choose the version your project needs

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
        run: npm run build

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false